version: "2"
services:
  dps: 
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      PYTHONPATH: "/usr/src/app"
    links:
      - postgres
    command: ./tasks/start_dps.sh

  postgres:
    image: postgres
    ports:
      - "5432:5432"
